name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        fetch-depth: 0
        
    - name: Generate version
      uses: paulhatch/semantic-version@v5.0.2
      with:
        tag_prefix: ""
        format: "${major}.${minor}.${patch}"
        
    - name: Create tag and push
      run: git tag ${{ steps.generate-version.outputs.version }} && git push --tags

    - name: Build
      run: |
        npm install
        npm run build
