name: main

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Packages
              run: |
                  npm install

            - name: Format and Lint
              run: |
                  npm run format
                  npm run lint

            - name: Build
              run: |
                  npm run build
            
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              with:
                branches: |
                  [
                    'main',
                    {
                      name: 'alpha',
                      prerelease: true
                    }
                  ]
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
