name: packaging

on:
    workflow_run:
        workflows: [pre-checks]
        types:
            - completed

jobs:
    packaging:
        if:
            ${{ github.ref_name == 'main' &&
            github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: debug
              run: |
                  ls
                  head ./build/manifest.json

            - name: Install dependencies
              run: |
                  npm ci

            - name: Release
              run: npx semantic-release --dry-run
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
