name: release

on:
    push:
      branches:
        - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          issues: write
          pull-requests: write
          id-token: write
          packages: write

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                token: ${{ secrets.RELEASE_PAT }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 'lts/*'
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Verify the integrity of provenance attestations and registry signatures
              run: npm audit signatures

            - name: Build
              run: npm run build

            - name: Release
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
              run: npx semantic-release
